name: ESLint

on: [pull_request, push]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: npm ci
        shell: bash
      - name: Add node_modules/.bin to PATH
        run: echo "export PATH=$(npm bin):$PATH" >> $GITHUB_ENV
        shell: bash
      - name: List node_modules/.bin
        run: ls -la $(npm bin)
        shell: bash
      - name: Run lint check
        run: npm run lint
        shell: bash
      - name: Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
